### ISSUE TITLE
It is intented to work with the states_machines-activerecord gem?

### ISSUE THREAD

**Issue by xxswingxx** [state-machines/state_machines-activemodel-observers#1]
Hi!

I've been testing this gem with `states_machines-activerecor` and while it is mostly OK, some thing is not working for me. Can a returned `false`  value in a  `before_` method of an observer stop the transition?

For example, I have an `ActiveRecord::Base` model with a  `deliver` event. which make a transition from the state `draft` to `sent`. In a model observer I have a `before_deliver`. I was expecting that, by returning false in that  `before_deliver`, the transition would stop, but for my surprise it didn't.

I'm used to the stop behaviour with [/pluginaweek/state_machine](https://github.com/pluginaweek/state_machine) but with this it seems not. Is this behaviour intended or is this gem not designed to work with ActiveRecord?

**Comment by JohnSmall** [comment]
I think this is seuros' extraction of the old state_machine gem to get it working with AR 4.2 and higher. And also to split out the observer behaviour. 

As he's doing it in his spare time, then we have to be good citizens and sort out our own fixes to any problems we find and submit pull requests.

**Comment by seuros** [comment]
I'm closing this issue since other users reported that this gem works perfectly. 
Thank you @JohnSmall  for your input.
